### ISSUE TITLE
Can't click on any menu items

### ISSUE THREAD

**Issue by frank26080115** [openmv/openmv-ide#86] opened 2020-08-08 08:25 UTC
Windows 10 Pro 64 bit, Version 10.0.19041 Build 19041

IDE version is 2.6.0

It works 99% of the time but something would happen, I don't know what causes it, but the IDE stopped letting me click on any menus. Please see attached video in uploaded zip file
[openmvide_cantclickbuttons.zip](https://github.com/openmv/openmv-ide/files/5044945/openmvide_cantclickbuttons.zip)

Closing the IDE is the only solution that I found

**Comment by kwagyeman** [comment] 2020-08-08 15:05
This is a known issue. It's related to qtcreator actually and the base ide I built off of. I don't know what causes it. I think it's a memory corruption however.

**Comment by frank26080115** [comment] 2020-08-10 19:18
err I keep getting bitten by this bug

I get that memory corruption bugs are like impossible to hunt down...

Would you consider actually having tabs? Also, using CTRL-TAB to cycle through tabs? It would help me keep working since I can still use CTRL-S to save.

And why can't I type into the serial terminal? Is that a bug? I have like a billion new files just to test like 5 lines of code that I should be just running in the terminal. Swapping between RealTerm and the IDE is a pain in the ass too so I'm not going to do that.

**Comment by kwagyeman** [comment] 2020-08-10 19:42
There's a plugin that I can add to Qtcreator to get tabs. It's like, alot of work. So, I have no plans to do that right now.

Use the Tools->Open Terminal Feature to get a terminal you can type in. Note that the main IDE debug function can't be connected at the same time. The default terminal is just a debug log since we don't have debug message support for serial input into the camera in debug mode. It's not a bug so much as it's not implemented at all. I can turn on typing in the IDE easily. But, a link to the camera to send data needs to be added. @iabdalkader. Can you think about adding a debug message path for this? Arudino may want it.

**Comment by kwagyeman** [comment] 2021-01-30 01:59
I found what causes this. Actually, the menu appears behind the IDE window. It's actually a bug in Qt. There's some literature online where the issue gets fixed in the very latest releases. I'll look into getting this fixed as it bothers me too. However, it's somewhat of a challenge to upgrade our IDE code base to the very latest. I'm not sure if I can work around without rebuilding Qt itself.

**Comment by YCSamSun** [comment] 2022-04-25 02:47
I still suffer this proble on ubuntu 20.04 version. Is there any solution for this?

**Comment by kwagyeman** [comment] 2022-04-25 04:38
I have to update the IDE qt backend. It's not fixable without a huge upgrade and spend weeks on it which I don't have right now.

**Comment by kwagyeman** [comment] 2023-07-08 01:22
Hi, this should be fixed with the latest IDE about to be released.

**Closed as completed by kwagyeman** 2023-07-08 01:22 UTC
Labels: bug, needs new qt
